#spring:
#  datasource:
#    username: root
#    password: 337+d7+d
#    url: jdbc:mysql://localhost:3306/springtest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver