server:
  port: 8080

person:
  lastName: sss
  age: 33
  boss: true
  birth: 2020/8/8
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
    - 999
  dog:
    name: 小狗
    age: 2
